version: 1.0.{build}

install:
  - cmd: set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - cmd: pip install --egg scons
  - cmd: pip install numpy==1.11.3 cython

build_script:
  - cmd: set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - cmd: call build.bat

artifacts:
  - path: 'cantera\*.msi'
    type: File

deploy:
  release: 'Cantera $(CT_VERSION)'
  description: 'Binaries uploaded by AppVeyor, build $(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: XzTEspXrLNiDQJs4mtdMB/dI2QdtPQ2iIMxfS9aQ24C6jXDIVS0DMjL0PbwWpZsN
  artifact: /cantera/.*.msi/
  draft: true
  prerelease: true
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: false

environment:
  CT_VERSION: 2.4.0b1
  GIT_PW:
    secure: ZDKGbBpWbzWubzWcf909xg==
  matrix:
    - PYTHON_LOC: C:\Python27
      PY_VER: 2.7
      BUILD_ARCH: 32
      BUILD_MATLAB: Y
    - PYTHON_LOC: C:\Python34
      PY_VER: 3.4
      BUILD_ARCH: 32
    - PYTHON_LOC: C:\Python35
      PY_VER: 3.5
      BUILD_ARCH: 32
    - PYTHON_LOC: C:\Python36
      PY_VER: 3.6
      BUILD_ARCH: 32
    - PYTHON_LOC: C:\Python27-x64
      PY_VER: 2.7
      BUILD_ARCH: 64
      BUILD_MATLAB: Y
    - PYTHON_LOC: C:\Python34-x64
      PY_VER: 3.4
      BUILD_ARCH: 64
    - PYTHON_LOC: C:\Python35-x64
      PY_VER: 3.5
      BUILD_ARCH: 64
    - PYTHON_LOC: C:\Python36-x64
      PY_VER: 3.6
      BUILD_ARCH: 64
